### ISSUE TITLE
Add network stats

### ISSUE THREAD

**Issue by devinrsmith** [DataDog/docker-dd-agent#10]
Docker would be a great solution for me if all of the metrics worked correctly. It was mentioned in the docs that network, process list, and cpu metrics might be incorrect. Can these limitations be fixed?

**Comment by hvolpers** [comment]
Hi, any news here? I'm running CoreOS and want to see at least the network traffic. I added an additional partition to the host and it is not showing up. I didn't find a hint in the code, as it looks like the agent always uses df -i / df -k which does not show everything as the /proc files are mounted under /host/proc (perhaps I missed something?!)

**Comment by korya** [comment]
Do you have any plans to support network metrics in near future? an approximate date when we can expect it? a month? a year?

**Comment by alq666** [comment]
@korya we hope to get them within a month or 2.

**Comment by tj** [comment]
:+1:

**Comment by alq666** [comment]
We have a version being tested that adds network metrics. We will make it available via the registry with a different tag.

**Comment by chr0n1x** [comment]
any plans on getting this into `master` or `latest` soon?

**Comment by alq666** [comment]
@hkaj can you check with @LotharSee what the status of this is?

**Comment by hkaj** [comment]
@alq666, @all we are currently working on a revamp of the docker check that will add new metrics (block IO, network) and new features, using docker-py. Of course the dockerized agent will keep up with these changes.
These modifications are set to be released with 5.5, and we'll offer beta testing when ready.

**Comment by chr0n1x** [comment]
@hkaj awesome, thanks!

**Comment by hkaj** [comment]
The new docker check `docker_daemon.py` answers to most of this. It went out with 5.5 and adds a lot of  new metrics and features. For more specific questions, please open new issues.

**Comment by jtblin** [comment]
@hkaj I have deployed the latest https://github.com/DataDog/docker-dd-agent but I'm still not getting the network metrics. The README of `docker-dd-agent` seems to indicate it's still missing / not working

> Known missing/incorrect metrics:
> * Network
> * Process list

Could you please confirm if it is supposed to be possible to get network metrics now? And if yes what needs to be done?

Thank you

**Comment by laurieodgers** [comment]
Since this is the #1 result on google for **docker dd-agent host network metrics**, here is how I solved it after searching through the source code:
- /proc from the host is mounted in at /host/proc as per the example in readme.md so this needs to be added to /etc/dd-agent/datadog.conf:
`procfs_path = /host/proc`
- the network checks are disabled by default in the docker dd-agent container so add it to /etc/dd-agent/conf.d/network.yaml:
```
init_config:
instances:
  - collect_connection_state: false
    excluded_interfaces:
      - lo
      - lo0
```
