### ISSUE TITLE
Docker container doesn't work - entrypoint.sh permissions error

### ISSUE THREAD

**Issue by akramhussein** [DataDog/docker-dd-agent#102]
Hi guys,

We've hit an issue today because we were using the 'ecs' tag of the docker container on DockerHub which is no longer working. The commit #83 I believe introduced an error, which means the container won't start. Our AWS ECS infrastructure stopped allowing us to deploy and we tracked it do it to this:

> 2016-06-27T15:07:39Z [WARN] Error with docker; stopping container module="TaskEngine" task="django-app:55 arn:aws:ecs:eu-west-1:931510279835:task/2a882630-f738-4704-b5c1-7e2c306de988, Status: (NONE->RUNNING) Containers: [dd-agent (RUNNING->RUNNING),app (NONE->RUNNING),consul (RUNNING->RUNNING),logspout (RUNNING->RUNNING),nginx (NONE->RUNNING),registrator (NONE->RUNNING),]" container="dd-agent(datadog/docker-dd-agent:ecs) (RUNNING->RUNNING)" err="API error (500): Cannot start container **0e7230dc3eef9e344270005404c6e82b50c1fd0d2c4d79535ec1e104fcdcf81d: [8] System error: exec: "/entrypoint.sh": permission denied**

For now I will try and use an older tag.

Akram

**Comment by hkaj** [comment]
Hey @akramhussein 
I pushed a fix, it should work now.
Sorry for the inconvenience.

**Comment by hkaj** [comment]
@akramhussein by the way, this tag is not useful anymore. It simply points to the master branch. You should replace it with `latest` as we're going to update the documentation and remove it after a deprecation period.
