### ISSUE TITLE
172.17.42.1 is no longer the default docker host (docker version 1.9+)

### ISSUE THREAD

**Issue by mhahn** [DataDog/docker-dd-agent#114]
lots of discussion here: https://github.com/docker/docker/issues/17305

Seems like https://github.com/docker/docker/issues/17305#issuecomment-201964626 is the recommend solution.

**Comment by remh** [comment]
Thanks for the heads up @mhahn .

It looks like there is still no official way to get the host ip from within a container :|

We have this pull request that will try a few things (but in the worst case scenario will fall back on 172.17.42.1)

**Comment by hkaj** [comment]
Closing as this PR was merged and no good solution has emerged yet to get the host IP. Of course we'll when such a method appears we'll happily adopt it.

Feel free to reopen if you have any comment/question.
