### ISSUE TITLE
ECS got stack due to too many open connection to docker socket.

### ISSUE THREAD

**Issue by driv3r** [DataDog/docker-dd-agent#119]
I was running datadog docker container as task service in ECS, today I've tried to update it, although I couldn't for some reason. After inspecting logs I found out that /var/run/docker.sock had too many open connections, a whole lot of entries about it actually - and from my containers only datadog task is having access to it. Any ideas?

```
...
2016-08-24T09:02:13Z [WARN] Error retrieving stats for container 849...831: dial unix /var/run/docker.sock: socket: too many open files
...
```

**Comment by hkaj** [comment]
Hi @driv3r 
Did your server run out of file descriptor? You might have a program that doesn't close its fd correctly.
It varies depending on your system but you can look at `/proc/sys/fs/file-nr` or equivalent to verify that.

**Comment by driv3r** [comment]
Ok will test it out after it will run some time and come back here.

**Comment by driv3r** [comment]
I think it's related to aws/amazon-ecs-agent/issues/362 with the same description testing newer agent version, closing this for now :+1:
