### ISSUE TITLE
Latest doesn't include 'master' changes

### ISSUE THREAD

**Issue by ensonik** [DataDog/docker-dd-agent#134]
I'm trying to get [this](https://github.com/DataDog/dd-agent/commit/e5302340f36f8a189e722a520ab6ba0e7afe633a#diff-0136fb05e6dae33960932ac0a7fb1521) in this docker image. 

- Using the `latest` tag doesn't include the change. 
- I tried including the `http_check.py` file manually in my custom Dockerfile build and have no success _(AttributeError("'HTTPCheck' object has no attribute 'proxies'",)_

What's the procedure to get this change? Do I need to wait for a new version of the agent to be published?

Thanks.

**Additional information you deem important (e.g. issue happens only occasionally):**
Here is my custom Dockerfile:

     FROM datadog/docker-dd-agent:latest
     RUN rm -f /etc/dd-agent/conf.d/*.yaml
     RUN rm -f /etc/dd-agent/conf.d/*.yaml.example
     COPY conf.d/http_check.yaml /etc/dd-agent/conf.d/http_check.yaml

- The http_check.yaml I'm copying over to the Docker image is fine (tested and works where there is no POST check)
- Once the image is started, to verify if the master changes are in (in other words, if the 'post' check is part of the image), I go to `/opt/datadog-agent/agent/checks.d/http_check.py` to see if they are there (which they aren't).

**Comment by hkaj** [comment]
Hi @ensonik 
Thanks for your interest.

The `latest` tag is actually pointing to the latest release tag (`11.0.591` as of now). Code from the master branch is not built into an image for now (we have a nightly tag that's supposed to have it but its build pipeline needs to be updated on our end).

Regarding the check you want to add, there's an option in the base image that should help, I'd suggest having a look here: https://github.com/DataDog/docker-dd-agent#configuration-files

Let me know if that helps.

**Comment by ensonik** [comment]
Thanks for the reply @hkaj . Unfortunately the suggested solution doesn't work. 

I've tried already and get `(AttributeError("'HTTPCheck' object has no attribute 'proxies'",)`. There are likely some dependencies that would also need to be included in the image. 

I'll wait for the change to be included in the image.

Thanks anyway.
