### ISSUE TITLE
[service discovery] Using weave in Docker Cloud

### ISSUE THREAD

**Issue by kimroen** [DataDog/docker-dd-agent#136]
When you are using Docker Cloud as your docker host, it comes with its own system for service discovery (I believe it's using [weave](https://www.weave.works/), like Kubernetes does). It seems like services discovery as a way of [discovering and enabling integrations](https://github.com/DataDog/docker-dd-agent#enabling-integrations) should be possible with this system.

I'm just starting to look in to setting up datadog with our infrastructure, and I was having problems getting the integration with haproxy to work, for example. Sorry if this is obvious and I'm just not understanding.

Thanks! :heart:

**Comment by hkaj** [comment]
Hi @kimroen 

Thanks for bringing this up! I was looking for a good reason to add a weave integration to the roadmap 😛 
Although for service discovery we already have an existing mechanism that you can read about [http://docs.datadoghq.com/guides/servicediscovery/](here). Does that fit your use case?

**Comment by kimroen** [comment]
I'm sure it does (I haven't started actually setting it up yet, because it seemed like a lot of work), but I wanted to make sure there wasn't a simpler way I was missing.

Using weave or not is not really something I care about as an end goal, and I don't think most users of Docker Cloud would know that that's what they are using. What I would love is for Datadog to automatically discover the services in use when using Docker Cloud. I have already defined all my Services there - it would be so awesome if I didn't have to define them again.

As for how to do it, I think looking at the [docker image for haproxy made specifically for Docker Cloud](https://github.com/docker/dockercloud-haproxy) could be interesting. It uses the Docker Cloud API to listen for new containers that are linked to it and automatically update its config to include them. In their words:

> The haproxy container will start querying Docker Cloud's API for an updated list of containers in the service and reconfigure itself automatically, including:
>
> - start/stop/terminate containers in the linked application services
> - start/stop/terminate/scale up/scale down/redeploy the linked application services
> - add new links to HAProxy
> - remove old links from HAProxy

I'm sure something like that would be possible for the Datadog agent as well, but I understand that things need to be prioritized 👍

**Comment by hkaj** [comment]
I see, thanks for expanding on this.
The main reason we're not doing this is that there are quite a few container platforms out there and we went with a more generic approach that fits with all of them.

I'll add your request to our backlog though, but it's not something we're planning on implementing in the short-term.

**Comment by kimroen** [comment]
> The main reason we're not doing this is that there are quite a few container platforms out there and we went with a more generic approach that fits with all of them.

Understood - I'm sure you have numbers about how many are using the various options 👍 

I'll check out the manual setup and see if I can make it work.

**Comment by kimroen** [comment]
@hkaj I'm closing this, considering [this aspect of Docker Cloud is shutting down on May 21st](https://docs.docker.com/docker-cloud/migration/). You could probably remove it from your roadmap as well 😉
