### ISSUE TITLE
Kubernetes kubelet auth

### ISSUE THREAD

**Issue by altvnk** [DataDog/docker-dd-agent#145]
In our installation (OpenShift) kubelet metrics endpoint is secured via TLS and has authentication/authorization via client cert and/or token. Is it possible to talk to secured kubelet from DD Agent? Did't found anything related in documentation/examples.

**Comment by tpolekhin** [comment]
+1

**Comment by mkozinenko** [comment]
+1

**Comment by hkaj** [comment]
Hi SoftServe folks,

Thank you guys for raising this issue. Authentication against the kubelet is not yet supported, but that's something we're interested in adding in the near future. I will add it to our backlog as a feature request. If it's a blocker for you and you have bandwidth to implement it yourself, I'd be happy to provide guidance and review a PR that implements it :)

In the meantime if you need Kubernetes metrics I suggest using the kubernetes_state integration that relies on the kube-state-metrics image. It's not as extensive as the Kubernetes integration but should still give you more visibility into your Openshift cluster.

Hope that helps, let me know if you have any other question.

**Comment by altvnk** [comment]
Thank you for such fast response. We definitely will check what we can do ourselves, if we have enough capacity for that ) Am i right that [checks.d/kubernetes.py](https://github.com/DataDog/dd-agent/blob/master/checks.d/kubernetes.py) is the right place for changes?

**Comment by hkaj** [comment]
there would certainly be some changes here yes, and the authentication logic should be in [https://github.com/DataDog/dd-agent/blob/master/utils/kubernetes/kubeutil.py](kubeutil.py).

**Comment by Lawouach** [comment]
+1 on that one as well!

**Comment by hkaj** [comment]
Hi everyone,

Quick update to let you know that we're starting working on this, so stay tuned!

**Comment by Lawouach** [comment]
Excellent news! :)

**Comment by netvisao** [comment]
+1

**Comment by iamrameshjonathan** [comment]
+1
