### ISSUE TITLE
Stale datadog/docker-dogstatsd image

### ISSUE THREAD

**Issue by rikonor** [DataDog/docker-dd-agent#147]
Hi,

Seems like the latest image for `datadog/docker-dogstatsd` on Docker Hub is at least a year old.
I can build the image myself, obviously, but expecting the hosted image to be up-to-date was a little confusing.

Might be worthwhile to update the latest image (or even tag them).

Or

**Comment by hkaj** [comment]
Hi @rikonor 
That's because this image is deprecated, please refer to https://github.com/DataDog/docker-dd-agent#standalone-dogstatsd for a standalone dogstatsd image.
Closing the issue but feel free to comment if you have any question.

**Comment by rikonor** [comment]
Hi @hkaj, thanks for the quick response.

I am talking about the standalone image for `dogstatsd`.
Although the [Dockerfile](https://github.com/DataDog/docker-dd-agent/blob/master/dogstatsd/Dockerfile) is fairly up-to-date - if you look at the [image page](https://hub.docker.com/r/datadog/docker-dogstatsd/tags/) on Docker Hub you can see that it was last updated about a year ago - meaning it's not up-to-date.

**Comment by rikonor** [comment]
OK, I understand now.

`dogstatsd` images are available under the general `agent` images. They're marked with `dogstatsd` in the tag.

Example: `datadog/docker-dd-agent:latest-dogstatsd`

It could just be me but you guys might want to consider making that clearer in the docs.

Thanks!

**Comment by hkaj** [comment]
Sorry I know it's a little confusing.

This docker hub repo is deprecated, its main pages states `This image is deprecated. Please run DogStatsD from docker-dd-agent instead.`: https://hub.docker.com/r/datadog/docker-dogstatsd/

Its source repository is https://github.com/DataDog/docker-dogstatsd which is not up to date. The folder you linked (https://github.com/DataDog/docker-dd-agent/tree/master/dogstatsd) is indeed up to date and is used to build dogstatsd tags as explained here: https://github.com/DataDog/docker-dd-agent#standalone-dogstatsd

Hope I cleared things up for you and didn't make it more obscure 😄
