### ISSUE TITLE
Automatically detect EC2 host IP for local consul agent when running in ECS

### ISSUE THREAD

**Issue by aantono** [DataDog/docker-dd-agent#151]
In the deployment scenario when a dd-agent running as docker container on ECS and the env variable `SD_CONFIG_BACKEND=consul` automatically assign the value of `curl http://169.254.169.254/latest/meta-data/local-ipv4` to `SD_BACKEND_HOST` env variable.  This would eliminate the need to have custom docker image to be built to dynamically detect this, since ECS does not support dynamic evaluation of variables, so no way to pass the host's ip and the default `127.0.0.1` does not work because the consul agent is not running inside the `dd-agent` container, but is either natively installed on the ECS host or runs as a separate docker container exposing consul ports to the outside.

**Comment by hkaj** [comment]
Hi @aantono 
I'm not sure this is something we should do. It's not going to work if consul is not running on every host where the dd-agent is deployed.
I think a better solution would be to have a load balancer (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-load-balancing.html) in front of consul and point the agent to that since it will be more static.

What do you think?

**Comment by aantono** [comment]
The consul agent is typically being deployed on every host in the ECS cluster, so it is listening on the expected `127.0.0.1:8500`, but the problem is that when this config is hardcoded for the `dd-agent`, which is deployed as a Docker container, the `127.0.0.1` for the `dd-agent` is actually referring to the localhost inside the dd-agent container and not the ECS host VM.  That's the reason for extracting the `local-ipv4` metadata to properly configure the agent.

The loadbalancer option is actually going against Consul deployment recommendations which states that one should not be talking to the Consul master servers for SD/KV needs but rather use the local host agent instead.  Additionally their SLB option is geared towards the containerized applications deployed on top of ECS, which does not apply to the Consul agent use-case, as it is a VM agent, guaranteed to be running on every host (if deployed correctly). And it is not really practical to create an ELB for every agent, plus that would kinda defeat the point.

Does my explanation make sense?

**Comment by hkaj** [comment]
I see, thanks for the detailed answer @aantono.
That makes plenty of sense, I'll add that to our backlog and will keep this issue updated about progress. Of course if you want to write a PR for it, feel free to :)

**Comment by aantono** [comment]
I wouldn't mind giving PR a try.  Any pointers on how to best do a local dev machine testing?

**Comment by hkaj** [comment]
Sure!

To make the agent think it's running on ECS you'll just need a dummy container named ecs-agent running, as you can see here: https://github.com/DataDog/dd-agent/blob/5.10.1/utils/dockerutil.py#L63-L71

You'll also need to run a consul container with the same config as on ECS.

And for testing the changes on the containerized dd-agent I think the easiest way would be to build a custom image based on `docker-dd-agent:latest` in which you would replace the default files of the agent (located in `/opt/datadog-agent/agent`) with your patched versions.

About how to proceed, the way I'd probably go is:
- introduce (and document in the comments) a special value for `sd_backend_host ` called `EC2_HOST_IP` or something [here](https://github.com/DataDog/dd-agent/blob/5.10.1/datadog.conf.example#L117-L118)
- then in [config_stores.py](https://github.com/DataDog/dd-agent/blob/5.10.1/utils/service_discovery/config_stores.py#L26) check for that and replace it with your suggestion if we're on ecs and containerized (you can check for that with `Platform.is_ecs_instance()` and `Platform.is_containerized()`)

Hope that helps.

**Comment by aantono** [comment]
@hkaj I've taken a first stab at the implementation.  I've decided not to go ahead and make the internal agent code changes, as that seemed a bit over the top for something so simple as variable config.  Instead I've opted to handle the logic in the startup shell, simply attempting to make a `curl` call to AWS meta-data service, and if it succeeds, use the value unless one is already explicitly set.  Let me know if you find this solution acceptable, I think it is very clean and not invasive, so no special handling logic is introduced into the agent code itself, keeping it simpler.

**Comment by hkaj** [comment]
Thanks @aantono, that's a good idea.

**Comment by aantono** [comment]
Updated the PR.
I was also thinking if it is necessary to limit `SD_CONFIG_BACKEND` to be only `consul`, or have it apply to `etcd` as well, since it would not be running on localhost either, so unless it is explicitly specified in the ENV var, would probably make sense to use the IP of the external host VM as well.  Thoughts?

**Comment by hkaj** [comment]
We can drop the `consul` condition indeed, any supported config backend works

**Comment by hkaj** [comment]
Fixed by #153 
It also works for etcd.
