### ISSUE TITLE
ERR_CONNECTION_REFUSED 8125/UDP

### ISSUE THREAD

**Issue by moltra** [DataDog/docker-dd-agent#152]
When I try and connect to the dd-agent remotely through the 8125/udp port.  I get an ERR_CONNECTION_REFUSED.

From Docker Shipyard I verified that they port is mapped

Exposed 172.18.0.3:8125 → 8125/udp

Here portion of the docker-compose.yml file that I am using to start the docker-dd-agent.

  dd-agent:
    image: datadog/docker-dd-agent
    container_name: dd-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - "8125:8125/UDP"
      - "9001:9001"
    environment:
      - VIRTUAL_HOST=dd.uorder.us
      - API_KEY={my key}

If you want to see the full yml file. At https://github.com/moltra/Docker_Nginx_Nginx-Proxy_LetsEncrypt_Shipyard_composer/blob/master/Docker_Nginx_Nginx-Proxy_Shipyard_Datadog.yml

**Comment by hkaj** [comment]
Hi @moltra 

Thanks for the feedback. Can you detail a little bit how you attempt to use this port? 8125 is used by dogstatsd in UDP mode so it's simply waiting for dogstatsd metrics and not expecting any connection.

If you aren't already familiar with dogstatsd you can learn more about it [here](http://docs.datadoghq.com/guides/dogstatsd/), about how to use it [here](http://docs.datadoghq.com/guides/metrics/) and about how it works in containerized environments [here](https://github.com/DataDog/docker-dd-agent/#standalone-dogstatsd).

**Comment by moltra** [comment]
I am learning how to use dockers, and I have a docker-compose.yml created to setup multiple docker containers and when those docker containers are setup. 

I was hoping to be able to see the graphs  right on the web server.  I might have miss understood the way your agent works,

**Comment by hkaj** [comment]
To see graphs you will need to connect to the website, the agent is only there collect metrics and act as a dogstatsd server to forward to our backend metrics you send to it (through port 8125 by default).

I'll close this issue as the behavior is expected, but feel free to open a new one if you find unexpected behavior or to reach out to support if you need help with using Datadog.
