### ISSUE TITLE
DataDog official containers do not include java

### ISSUE THREAD

**Issue by alexouzounis** [DataDog/docker-dd-agent#159]
Currently, the official DataDog dd-agent containers do not include java. That means that for any JMX integrations, we need to fork this repo, install java and build our own dd-agent container.

Would it possible to create a java/jmx variation of the dd-agent and push it to dockerhub ?

**Comment by hkaj** [comment]
Hi @alexouzounis 
That's a good point. We were actually planning on providing one as soon as service discovery would work officially with JMX integrations, but we can start now.

**Comment by alexouzounis** [comment]
Awesome work guys, really appreciated!
