### ISSUE TITLE
systemd unit file for running dd-agent in CoreOS 

### ISSUE THREAD

**Issue by korya** [DataDog/docker-dd-agent#16]
Just in case someone needs it, I share a simple systemd service file for running dd-agent in CoreOS:

```systemd
# vim: ft=systemd sw=2 et :

[Unit]
Description=Datadog Agent
After=docker.service
Requires=docker.service

[Service]
Restart=always
RestartSec=15

EnvironmentFile=/etc/environment
Environment=API_KEY=<YOUR_API_KEY>

ExecStartPre=-/usr/bin/docker stop dd-agent
ExecStartPre=-/usr/bin/docker rm -f dd-agent
ExecStartPre=/usr/bin/docker pull datadog/docker-dd-agent

ExecStart=/bin/bash -c ' \
  set -ex; \
  docker run --name dd-agent \
    --privileged \
    -h $HOSTNAME \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /proc/mounts:/host/proc/mounts:ro \
    -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
    -e API_KEY=$API_KEY \
    datadog/docker-dd-agent; \
'

ExecStop=-/usr/bin/docker stop dd-agent
ExecStop=-/usr/bin/docker rm -f dd-agent

[X-Fleet]
Global=true
```

**Comment by alq666** [comment]
Thanks @korya 

I think we can run without `privileged` now.

**Comment by korya** [comment]
Thanks for the tip. Indeed it works without the `privileged`.

The only problem I have is that no network metrics are reported. I'm running dd-agent in a cluster of 4 CoreOS hosts using this unit file. Is that the expected behavior? If yes, is it possible to configure it to report network metrics?

**Comment by alq666** [comment]
@korya it is until we add support for docker stats (on docker 1.5). Stay tuned.

**Comment by korya** [comment]
OK. Thanks for the information.

**Comment by mieciu** [comment]
@korya  -> that should definitely be in the repository, great work!! :+1:

**Comment by alq666** [comment]
I've added the service file here: https://github.com/DataDog/docker-dd-agent/blob/master/dd-agent.service
