### ISSUE TITLE
docker container or omnibus (?) doesn't support us-east-2.

### ISSUE THREAD

**Issue by gswallow** [DataDog/docker-dd-agent#164]
Boto 2.43 supports us-east-2, which is where I'm demoing datadog.  The container (v11.1.5101) uses boto 2.39.

**Comment by hkaj** [comment]
Hi @gswallow 
Thanks for the report, though could you open this issue against the [dd-agent repo](https://github.com/DataDog/dd-agent) instead? This does not concern the docker image specifically.

Thanks again
