### ISSUE TITLE
Flag to send all logs to stdout/stderr

### ISSUE THREAD

**Issue by mausch** [DataDog/docker-dd-agent#174]
It would be great to have a flag to send all logs (collector/forwarder/etc) to stdout/stderr instead of just supervisord.

Having to docker-exec into the container is especially cumbersome when deploying to kubernetes.
Currently, when something goes wrong with the datadog agent I have to:

1. Go to the datadog pod in the k8s dashboard to figure out the node where it's running.
1. SSH into the node
1. Figure out what the actual container is called (e.g. `docker ps | grep dd-agent`).
1. docker-exec to get the logs (e.g. `docker exec -it  k8s_dd-agent.b367b56c_dd-agent-env-1740366152-qi9d1_kube-system_a27f3de6-efb6-11e6-98ec-0a3b965b1a55_6b215580 sh -c 'cat /var/log/datadog/collector.log'`)

With the flag I propose I could just browse the logs in the k8s dashboard.

**Comment by hkaj** [comment]
Hi @mausch 
Agreed, that's something we have been thinking about for a while but didn't implement for lack of traction mostly. That should probably be the default actually, logging is a little painful in the containerized agent right now.

I'll add this to our backlog, in the meantime if you (or someone else reading this) want to give it a shot, feel free to :)

On a side note, you can probably reduce your first 3 steps with `kubectl exec -it <dd-agent-pod-id> bash`.
