### ISSUE TITLE
issue with kubernetes integration nstance #0[ERROR]:"HTTPConnectionPool(host='10.2.0.1', port=10255): Max retries exceeded

### ISSUE THREAD

**Issue by alirezaDavid** [DataDog/docker-dd-agent#177]
i got this error in data dog console when run datadog agent with `kubernetes: yes` (kubernetes daemonset):

```
nstance #0[ERROR]:"HTTPConnectionPool(host='10.2.0.1', port=10255): Max retries exceeded with url: /pods/ (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f931826a610>, 'Connection to 10.2.0.1 timed out. (connect timeout=10)'))"
```
I am using cni network plugin for kubernets, i think issue related to this part of documents:

```
the kubelet API endpoint is assumed to be the default route of the container, you can override the kubelet API endpoint by specifying KUBERNETES_KUBELET_HOST (eg. when using CNI networking, the kubelet API may not listen on the default route address)
```
But i dont know what should i do.
Thanks

**Comment by hkaj** [comment]
Hi @alirezaDavid, thanks for the feedback.
I think what is happening here is that the default gateway of the dd-agent container doesn't point to the underlying node with the CNI plugin, so querying kubelet fails.

Do you know if there's a preferred way to reach the host with this plugin? If so we could implement that, or if it has a static, known address you could set it in `kubernetes.yaml` through a ConfigMap.

If not we may be able to use the hostname for this, or an env variable. Could you `kubectl exec` into an dd-agent pod and send us the result of:
- `env` (make sure to strip sensitive info from it, like the `API_KEY` variable)
- `PYTHONPATH=/opt/datadog-agent/agent/ /opt/datadog-agent/embedded/bin/python -c "from utils.dockerutil import DockerUtil;print DockerUtil().client.info()['Name']"`.

The second one prints the docker hostname which we may be able to use to access the host. To verify that, you can run `/opt/datadog-agent/embedded/bin/curl http://$DOCKER_HOSTNAME:10255/pods` (just replace `$DOCKER_HOSTNAME` with the result of the previous command).

If that doesn't work we'll explore other options.

**Comment by alirezaDavid** [comment]
I think in my environment port 10255 just listen on localhost, and also i think datadog agent try connecting to 10255. Can i use port 10250?

by the way this is `env` output:

```
AGENT_VERSION=1:5.10.1-1
DOCKER_DD_AGENT=yes
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT=tcp://10.3.0.1:443
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_HOST=10.3.0.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
HOME=/root
KUBERNETES_SERVICE_PORT_HTTPS=443
SD_BACKEND=docker
KUBERNETES_PORT_443_TCP_ADDR=10.3.0.1
KUBERNETES_PORT_443_TCP=tcp://10.3.0.1:443
KUBERNETES=yes
```

and the output of this command:

```
PYTHONPATH=/opt/datadog-agent/agent/ /opt/datadog-agent/embedded/bin/python -c "from utils.dockerutil import DockerUtil;print DockerUtil().client.info()['Name']".
```

`worker-3`

and output of this:

```
/opt/datadog-agent/embedded/bin/curl http://worker-3:10255/pods
```
is
`curl: (6) Couldn't resolve host 'worker-3'`

**Comment by hkaj** [comment]
Thanks.
You can use 10250 if it doesn't require authentication, just exec into an agent pod replace the port in `/etc/dd-agent/conf.d/kubernetes.yaml` (you will need to apt-get install vim) and restart the collector with `/opt/datadog-agent/bin/supervisorctl -c /etc/dd-agent/supervisor.conf restart datadog-agent:collector`. 
If that works you can replace that directly in the image by building your own, or use [this trick](https://github.com/DataDog/docker-dd-agent#configuration-files) and mount the working file in a Kubernetes ConfigMap.

But 10255 should work if you didn't disable the read-only port in kubelet config. In other words, if you start kubelet with `--read-only-port=0` it won't work. Is it the case?

If neither 10250 nor 10255 work it's a hostname resolution issue, let me know if it's the case and we'll find what works in your setup.

**Comment by alirezaDavid** [comment]
Hi @hkaj 
My issue still there.
I change port to 10250 but it doesn't work.
What is `KUBERNETES_KUBELET_HOST` and how can i find out kubelet host?
I thinks issue related to CNI networking, but i can't find the solution.
Thanks

**Comment by alirezaDavid** [comment]
UPDATE: SOLUTION
Ok, thanks to @hkaj 
My problem is iptable rules.
when open cni0 input, the problem is solved.
Thanks

**Comment by hkaj** [comment]
glad you got it to work!
