### ISSUE TITLE
issue with service discovery in kubernetes cluster

### ISSUE THREAD

**Issue by alirezaDavid** [DataDog/docker-dd-agent#182]
I want add nginx integration to service discovery `auto_conf` folder
i have kubernets cluster and use datadog `daemonset` for datadog agent.
i `exec` one of the datadog agent  and add nginx.yaml to `/etc/dd-agent/conf.d/auto_conf/nginx.yaml`, but doesn't worke.
this is my `nginx.yaml` file:

```
docker_images:
  - private.repo.io/boo/awesome

init_config:

instances:
  - nginx_status_url: http://%%host%%/basic_status
```

**Comment by hkaj** [comment]
Hi @alirezaDavid 
you will need to restart the collector for this to work. Config files are not picked up automatically, they need to be there when the collector starts. Problem is, if you restart the agent completely it will stop the container and erase your changes, so you shouldn't restart supervisor but only the collector. You can run `/opt/datadog-agent/bin/supervisorctl restart datadog-agent:collector` for that. Then your check should run (verify it with `service datadog-agent info`)

**Comment by alirezaDavid** [comment]
@hkaj Thanks 
I try `/opt/datadog-agent/bin/supervisorctl restart all` and still pod (container) working and doesn't killed.
but this config doesn't work.
```
docker_images:
  - private.repo.io/boo/awesome

init_config:

instances:
  - nginx_status_url: http://%%host%%/basic_status
```
should i using image name with tag in `docker_image` directive?

**Comment by alirezaDavid** [comment]
**UPDATE**
my issue solved by change image name from `private.repo.io/boo/awesome` to `awesome`.
Thanks
