### ISSUE TITLE
The dogstatsd only image doesn't support APM tracing.

### ISSUE THREAD

**Issue by GrahamDumpleton** [DataDog/docker-dd-agent#199]
The image ``datadog/docker-dd-agent:latest-dogstatd`` doesn't appear to support APM tracing.

Full image does:

https://github.com/DataDog/docker-dd-agent/blob/master/Dockerfile#L17

```
# Configure the Agent
# 1. Listen to statsd (8125) and traces (8126 and 7777) from other containers
# 2. Turn syslog off
# 3. Remove dd-agent user from supervisor configuration
# 4. Remove dd-agent user from init.d configuration
# 5. Fix permission on /etc/init.d/datadog-agent
RUN mv /etc/dd-agent/datadog.conf.example /etc/dd-agent/datadog.conf \
 && sed -i -e"s/^.*non_local_traffic:.*$/non_local_traffic: yes/" /etc/dd-agent/datadog.conf \
 && sed -i -e"s/^.*log_to_syslog:.*$/log_to_syslog: no/" /etc/dd-agent/datadog.conf \
 && sed -i "/user=dd-agent/d" /etc/dd-agent/supervisor.conf \
 && sed -i 's/AGENTUSER="dd-agent"/AGENTUSER="root"/g' /etc/init.d/datadog-agent \
 && rm /etc/dd-agent/conf.d/network.yaml.default \
 || chmod +x /etc/init.d/datadog-agent

# Expose DogStatsD, supervisord and trace-agent ports
EXPOSE 8125/udp 9001/tcp 8126/tcp 7777/tcp
```

The dogstatsd image only does:

https://github.com/DataDog/docker-dd-agent/blob/master/dogstatsd/Dockerfile#L18

```
# Configure the Agent
# 1. Listen to statsd from other containers
# 2. Turn syslog off
# 3. Use custom supervisor.conf
RUN mv /etc/dd-agent/datadog.conf.example /etc/dd-agent/datadog.conf \
 && sed -i -e"s/^.*non_local_traffic:.*$/non_local_traffic: yes/" /etc/dd-agent/datadog.conf \
 && sed -i -e"s/^.*log_to_syslog:.*$/log_to_syslog: no/" /etc/dd-agent/datadog.conf \
 && mv /supervisor.conf /etc/dd-agent/supervisor.conf

# Expose supervisor and DogStatsD port
EXPOSE 9001/tcp 8125/udp
```

When using ``datadog/docker-dd-agent:latest-dogstatd`` as a sidecar container in OpenShift it would be advantageous to also have the APM capability available in the image. IOW, the image should be runnable as non root and do everything except server monitoring. So shouldn't be just dogstatsd.

**Comment by hkaj** [comment]
Hi @GrahamDumpleton thanks for reaching out.
This is something the APM team could answer better than me. @talwai could you or someone from the team have a look? Ping me if you need more context.

**Comment by awang** [comment]
Hi @GrahamDumpleton sorry for the delay -- we've got this task queued up, should have a fix out for you sometime next week (before PyCon)

**Comment by irabinovitch** [comment]
The dogstatsd-latest tag now includes the trace-agent.
