### ISSUE TITLE
Define Kubernetes namespaces for events collection

### ISSUE THREAD

**Issue by mazzy89** [DataDog/docker-dd-agent#215]
At the moment it's quite hard to define Kubernetes namespaces during configuration process. By default only events produced in `default` namespace are pushed to DD. I'm thinking to design a way to define namespace. Via environment variables I'd say it's not recommended. Any proposals?

**Comment by hkaj** [comment]
Hi @mazzy89, thanks for reaching out.
What's wrong with https://github.com/DataDog/docker-dd-agent/blob/master/entrypoint.sh#L147-L156 in your opinion?

**Comment by mazzy89** [comment]
So If I didn't understand wrong If I define:

`KUBERNETES_NAMESPACE_NAME_REGEX=*`

I should be able to get logs from all the namespaces? Am I right?

**Comment by mazzy89** [comment]
```
# The namespaces for which events should be collected.
  # If not modified, the 'default' namespace will be used.
  #
  # namespaces:
  #  - default

  # The regexp used to select namespaces for which events should be collected.
  # The matched namespaces will be added to the "namespaces" list.
  # If empty, regexp selection will be ignored.
  #
   namespace_name_regexp: *
```

this is the result of the configuration after set up the env var `KUBERNETES_NAMESPACE_NAME_REGEX=*` but currently no event is collected @hkaj missing anything?

**Comment by mazzy89** [comment]
Right regex `.` now it finally works. Thanks @hkaj to point out. I didn't understand from the doc that it was ussed in that way.
