### ISSUE TITLE
Limitations still valid?

### ISSUE THREAD

**Issue by jvassev** [DataDog/docker-dd-agent#22]
The doc states the Process/Network picture the agent sees is unreliable (https://github.com/DataDog/docker-dd-agent#limitations)
Is this still true if the agent container is run with --pid=host (since docker-1.5.0)

**Comment by alq666** [comment]
@LotharSee can you weigh in on this? /cc @remh

**Comment by LotharSee** [comment]
`--pid=host` might be our solution yes, thanks for sharing this idea!
I will test it to ensure that there is no downside, then document it if it works!

**Comment by xintron** [comment]
Wouldn't setting `--net="host"` allow for full network monitoring as well? It would remove the ability to link other containers and also only allow dogstatsd to bind one time (unless you add the ability to specify port using an environment variable or similar) but all network interfaces would be available from inside the container and thus logging of that data would work as expected.

**Comment by remh** [comment]
Using `--net=host` and `--pid=host` would work yes. Unfortunately it would mean that the Agent container would have root access to these processes.

As a result it could kill a root owned process on the host, reboot the host, etc. etc..

We should document how to enable those features but not recommend them.
cc: @hkaj

**Comment by hkaj** [comment]
Yes we already explored this option, and actually received a PR about it: https://github.com/DataDog/docker-dd-agent/pull/26
The thing is, it goes against containerization (respectively of network interfaces and PIDs) and is not recommended in our use case. I will write a wiki page about it, so that people who want to use these options know about them, and about the risks.

**Comment by hkaj** [comment]
more info available here: https://github.com/DataDog/docker-dd-agent/wiki
re-open if you have any other question about that.
