### ISSUE TITLE
DD_HOSTNAME environment variable is not working with dogstatsd only images

### ISSUE THREAD

**Issue by nimeshksingh** [DataDog/docker-dd-agent#221]
The entrypoint.sh scripts (for both the alpine and ubuntu versions of the dogstatds only image) is missing the logic to set the hostname configuration option from DD_HOSTNAME environment variable.

**Comment by xvello** [comment]
Hi @nimeshksingh,

Thanks for catching that! `latest` images are currently rebuidling, and the new mapping should be available as soon as [the build](https://hub.docker.com/r/datadog/docker-dd-agent/builds/) finishes.

Regards

**Comment by drozzy** [comment]
Still not working in.. 6.4.1 for me...

**Comment by xvello** [comment]
Hi @drozzy 

This `docker-dd-agent` repository is the packaging of Agent5. You are referring to Agent6 6.4.1, that is a complete rewrite and lives in https://github.com/DataDog/datadog-agent

I just confirmed `datadog/dogstatsd:6.4.1` reacts to the value of the `DD_HOSTNAME` environment variable. Please keep in mind this hostname is only added if no hostname is already specified at metric submission. If that still does not work for your use case, please contact [our support team](https://www.datadoghq.com/support/).

**Comment by drozzy** [comment]
> Please keep in mind this hostname is only added if no hostname is already specified at metric submission

Thank you this clarifies it!
