### ISSUE TITLE
Alpine docker image runs entrypoint with set -x, emits secrets into logs.

### ISSUE THREAD

**Issue by dreamlibrarian** [DataDog/docker-dd-agent#227]
**Additional environment details (Operating System, Cloud provider, etc):**

Docker 17.06

**Steps to reproduce the issue:**

1. Start docker-dd-agent:alpine-latest
2. watch stdout.

**Describe the results you received:**

API key shows up in output as part of bash -x stream

**Describe the results you expected:**

Secrets should not show up in stdout.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by aerostitch** [comment]
I guess this can be closed now as #226 has been merged right?
