### ISSUE TITLE
Could I set performance_tags on starting up this image?

### ISSUE THREAD

**Issue by buzztaiki** [DataDog/docker-dd-agent#235]
Hi.

I want to set performance_tags configuration variable into container on starting up this image.
Could I set it except customize datadog.conf? Are you plan for this feature?

**Comment by xvello** [comment]
Hi @buzztaiki,

The recommended way to override this option is to write your own `docker_daemon.yaml` conf file. You can either:
  - build it in a custom docker image, see the `examples` folder
  - mount a `/conf.d` folder in the container, the entrypoint will detect the conf file and use it
  - if you use Kubernetes, you can store this config file in a configmap and directly mount it in `/conf.d/docker_daemon.yaml`

**Comment by buzztaiki** [comment]
OK, Thanks.
