### ISSUE TITLE
Current release version not tagged on Docker registry

### ISSUE THREAD

**Issue by lachlancooper** [DataDog/docker-dd-agent#271]
Version 12.5.5202 was released 3 days ago and new images were pushed to the Docker registry at the time. However only the various `latest-` tags were added, so there's no numbered versions like `12.5.5202`, `12.5.5202-alpine`, etc.

https://hub.docker.com/r/datadog/docker-dd-agent/tags/

I build a custom image from a pinned version (rather than `latest`) so I would appreciate having those tagged versions available. I expect the release process just needs a small tweak.

**Comment by hkaj** [comment]
Hi @lachlancooper 
Thanks for the heads-up, looks like we forgot to push the button for this part of the release. Should be good now.
