### ISSUE TITLE
Bump dd-agent to >=6.0

### ISSUE THREAD

**Issue by discordianfish** [DataDog/docker-dd-agent#272]
Looks like there is no docker image for >=6.0 which is required to use the new (beta) logging feature.

**Comment by hkaj** [comment]
Hi @discordianfish 
You're looking for https://github.com/DataDog/datadog-agent/tree/master/Dockerfiles/agent

Enjoy the sweet log monitoring 😃

**Comment by mattwilliamson** [comment]
What's the difference between that docker image and this one? Can I deploy that one on rancher from the catalog somehow?

**Comment by irabinovitch** [comment]
One builds dd-agent 5.0 the other builds datadog-agent 6.0+.
6.0 includes logs and other new features currently in beta. They are not yet available in the catalog.
