### ISSUE TITLE
docker_daemon.yaml 

### ISSUE THREAD

**Issue by sarkistlt** [DataDog/docker-dd-agent#275]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
(paste your output here)
```

**Additional environment details (Operating System, Cloud provider, etc):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by antoinepouille** [comment]
This seems like an error while editing issue #276. Closing
