### ISSUE TITLE
dash in front of comment should be on url line?

### ISSUE THREAD

**Issue by sedlund** [DataDog/docker-dd-agent#277]
https://github.com/DataDog/docker-dd-agent/blob/d48ecb58ccdc7936f9c00ed45e68fffe7212280f/conf.d/docker_daemon.yaml#L24

should the dash (-) on line 24 be on line 30?

**Comment by antoinepouille** [comment]
Hi @sedlund,

There is no need to have the dash on the same line as the entry, and a comment is totally fine here.
However, you may also use the dash on line 30.
You can check the validity of a YAML file by using [this online tool](http://yaml-online-parser.appspot.com/).

I'll be closing this issue, but if you still need help, please [open a new support case](https://www.datadoghq.com/support/) where we will be able to assist you.

Regards
