### ISSUE TITLE
I have one swarm and 5 nodes do we need to run the DD docker in nodes also or running in swarm will fetch the metrics from nodes 

### ISSUE THREAD

**Issue by SIVA451** [DataDog/docker-dd-agent#278]
In each node there are 5 docker images running, Can I monitor all 5 docker metrics from with single DD docker in swarm.

**Comment by antoinepouille** [comment]
Hi @SIVA451 ,

Yes, you should be able to run the agent on swarm, and monitor your different containers.
In sum-up, you would need to modify this line of the config: https://github.com/DataDog/docker-dd-agent/blob/11.0.573/conf.d/docker_daemon.yaml#L30
to use the node IP/name. There are two ways of doing so: baking that in a custom image on top of ours or using these instructions to override the default docker_daemon.yaml with your own file: https://github.com/DataDog/docker-dd-agent#enabling-integrations.

If you have issues following these steps, please [open a new support case](https://www.datadoghq.com/support/) where we will be able to help.
