### ISSUE TITLE
Easier config changes for docker_daemon.yaml

### ISSUE THREAD

**Issue by hibbert** [DataDog/docker-dd-agent#279]
**Steps to reproduce the issue:**

Had to provide my own docker_daemon.yaml as a custom check, mounted to the container, this is okay but I made a relatively minor change which was to set collect_disk_stats to true

**Describe the results you received:**

Worked okay

**Describe the results you expected:**

Be able to change some stuff in the docker_daemon.yaml via environment variables, this would be preferable as these config items and default settings are likely to change in newer versions of the datadog agent 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by antoinepouille** [comment]
Hi @hibbert,

Thanks for reaching out!

Mounting a single YAML file to the container is a valid way to get your checks loaded in the agent, but we usually advise a different way, about you can read in [this paragraph](https://github.com/DataDog/docker-dd-agent#configuration-files) of the documentation: 

> You can also mount YAML configuration files in the /conf.d folder, they will automatically be copied to /etc/dd-agent/conf.d/ when the container starts. The same can be done for the /checks.d folder. Any Python files in the /checks.d folder will automatically be copied to /etc/dd-agent/checks.d/ when the container starts.
> 
>     Create a configuration folder on the host and write your YAML files in it. The examples below can be used for the /checks.d folder as well.
> 
>     mkdir /opt/dd-agent-conf.d
>     touch /opt/dd-agent-conf.d/nginx.yaml
> 
>     When creating the container, mount this new folder to /conf.d.
> 
>     docker run -d --name dd-agent \
>       -v /var/run/docker.sock:/var/run/docker.sock:ro \
>       -v /proc/:/host/proc/:ro \
>       -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
>       -v /opt/dd-agent-conf.d:/conf.d:ro \
>       -e API_KEY={your_api_key_here} \
>       datadog/docker-dd-agent
> 
>     The important part here is -v /opt/dd-agent-conf.d:/conf.d:ro
> 
> Now when the container starts, all files in /opt/dd-agent-conf.d with a .yaml extension will be copied to /etc/dd-agent/conf.d/. Please note that to add new files you will need to restart the container.

Using these steps, you should be able to avoid using environment variables to set the configuration.

I'll be closing this issue, but if you need help following these steps, please [open a new support case](https://www.datadoghq.com/support/) where we will be able to assist you.
