### ISSUE TITLE
Invalid user dd-agent 

### ISSUE THREAD

**Issue by groenator** [DataDog/docker-dd-agent#283]
Hi,

I am trying to build a container with the dd-agent. I add my own checks and configurations. However, I am encountering some issues with the dd-agent user. 

Every time when I start the container I get this error. 

`Error: Invalid user name dd-agent in section 'program:forwarder' (file: '/etc/dd-agent/supervisor.conf')`

Dockerfile:

`FROM debian:jessie

ENV DOCKER_DD_AGENT=yes \
    AGENT_VERSION=1:5.21.2-1 \
    AGENTUSER="dd-agent" \
    DD_ETC_ROOT=/etc/dd-agent \
    PATH="/opt/datadog-agent/embedded/bin:/opt/datadog-agent/bin:${PATH}" \
    PYTHONPATH=/opt/datadog-agent/agent \
    DD_CONF_LOG_TO_SYSLOG=no \
    DD_LOG_ENABLED=true \
    DD_HOSTNAME=test-datadog-mon-001 \
    NON_LOCAL_TRAFFIC=no \
    DD_LOGS_STDOUT=yes \
    DD_SUPERVISOR_DELETE_USER=no

# Install the DataDog Agent & Jinja2
# https://app.datadoghq.com/account/settings#agent/ubuntu
RUN echo "deb http://apt.datadoghq.com/ stable main" > /etc/apt/sources.list.d/datadog.list \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C7A7DA52 \
    && apt-get update \
    && apt-get install --no-install-recommends -y datadog-agent="${AGENT_VERSION}" \
    && apt-get install --no-install-recommends -y ca-certificates \
    && apt-get install --no-install-recommends -y python-jinja2 \
    && apt-get install --no-install-recommends -y apt-utils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Add our code and configuration
ADD etc /etc
ADD scripts/* /

# dd-agent ships its own supervisord, we need to use this
ENV PATH="/opt/datadog-agent/embedded/bin:/opt/datadog-agent/bin:${PATH}"

# Fix permissions on /etc/init.d/datadog-agent.
RUN sed -i 's/AGENTUSER="dd-agent"/AGENTUSER="root"/g' /etc/init.d/datadog-agent \
  && rm -f ${DD_ETC_ROOT}/conf.d/network.yaml.default

# Default configuration values can be overridden using Docker env vars
ENV METRIC_PREFIX="test"
ENV ENVIRONMENT="dev"

# Extra conf.d and checks.d
VOLUME ["/conf.d", "/checks.d"]

# Expose DogStatsD and trace-agent ports
EXPOSE 8125/udp 8126/tcp

ENTRYPOINT ["/entrypoint.sh"]
CMD ["supervisord", "-n", "-c", "/etc/dd-agent/supervisor.conf"]`

Can anyone advise what I've done wrong here? 

**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
(paste your output here)
```

**Additional environment details (Operating System, Cloud provider, etc):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by groenator** [comment]
This issue can be closed. I found the problem to be with some global variables that I have exported.

**Comment by jegonzalez** [comment]
can you explain which global variables were the ones causing this error?, I think I'm facing the same here .

**Comment by groenator** [comment]
Hi, it's being a long time. I don't remember what variables were...Sorry buddy...
