### ISSUE TITLE
Windows DD agent Version 6.1.1 - Issues

### ISSUE THREAD

**Issue by SIVA451** [DataDog/docker-dd-agent#303]
While testing the agent V6 on windows, I have seen that agent not opening in the browser.

As a part of the testing, I have installed the 5.6v later downloaded and executed the EXE installer to update the agent to the newer version. After this, we have downloaded and installed the agent 6.1.1 from https://github.com/DataDog/datadog-agent/releases.

Kindly, help us to fix this. Thanks in advance.

**Comment by SIVA451** [comment]
Do we have any solution or plan to fix in next version.

**Comment by hkaj** [comment]
Hi @SIVA451 
This is the repository for the docker image of the agent 5.x version. I think you are looking for the agent 6 repository: https://github.com/DataDog/datadog-agent/

**Comment by SIVA451** [comment]
My main concern is DD team mentioned that agent v6 is cross-browser in windows, Now agent is not opening the browser.

FYI: We have to do it for more than 200 servers, we are leveraging on the PowerShell script to do all these. automatically.
