### ISSUE TITLE
Cannot stop and start docker container

### ISSUE THREAD

**Issue by rootd00d** [DataDog/docker-dd-agent#305]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Steps to reproduce the issue:**
1.  Start the Datadog agent container
2.  Stop the Datadog agent container
3.  Attempt to start the Datadog agent container

The container is not able to restart, giving the following error --

```
mv: cannot stat '/etc/datadog-agent/conf.d/docker.d/conf.yaml.example': No such file or directory
[cont-init.d] 51-docker.sh: exited 1.
```

I, of course, just expected the container to be able to start.  This appears to be a result of the lines 22 and 23, where it moves the a file with extension .example to .default --

```
/etc/cont-init.d/51-docker.sh:
  1 #!/bin/bash
  2 #
  3 # We enable docker if either:
  4 #   - we detect the DOCKER_HOST envvar, overriding the default socket location
  5 #     (in that case, we trust the user wants docker integration and don't check existence)
  6 #   - we find the docker socket at it's default location
  7
  8 if [[ -z "${DOCKER_HOST}" && ! -e /var/run/docker.sock ]]; then
  9     exit 0
 10 fi
 11
 12
 13 # Set a config for vanilla Docker if no orchestrator was detected
 14 # by the 50-* scripts
 15 # Don't override /etc/datadog-agent/datadog.yaml if it exists
 16 if [[ ! -e /etc/datadog-agent/datadog.yaml ]]; then
 17     ln -s  /etc/datadog-agent/datadog-docker.yaml \
 18            /etc/datadog-agent/datadog.yaml
 19 fi
 20
 21 # Enable the docker corecheck
 22 mv /etc/datadog-agent/conf.d/docker.d/conf.yaml.example \
 23    /etc/datadog-agent/conf.d/docker.d/conf.yaml.default
```

Since the file will have already been moved the first time the container started, it will not be able to find the file the next time the container starts; which seems to cause s6-supervise to fail to load correctly.

Consider moving this to a `cp` command instead.

**Comment by xvello** [comment]
Hello @rootd00d ,

This should be addressed by 6.1.3, released today, see https://github.com/DataDog/datadog-agent/pull/1541
