### ISSUE TITLE
Host Tags in K8s YAML not working as expected

### ISSUE THREAD

**Issue by TheMagoo73** [DataDog/docker-dd-agent#319]
**Description**

Using the `DD_TAGS` environment variable to configure the agent as part of the agent `daemonset` installation doesn't seem to add tags as described in the documentation. Separating tags with a comma as described seems to result in the creation of a single host tag, with the commas replaced by underscores. Using `datadog/agent:latest`.

**Additional environment details (Operating System, Cloud provider, etc):**
Running in GKE, within the Google Cloud Platform. 

**Steps to reproduce the issue:**
Modify the K8s manifest for the agent daemon install to use the `DD_TAGS` environment variable to add additional host tags:

```yaml
- name: DD_TAGS
  value: env:staging,support:johnc
``` 

**Describe the results you received:**
Nodes have the single additional host tag `env:staging_support:johnc`

**Describe the results you expected:**
Node to have two additional tags `env:staging` and `support:johnc`

**Comment by hkaj** [comment]
Hi @TheMagoo73 
Could you re-open this issue in the [agent 6 repository](https://github.com/DataDog/datadog-agent/)? This repo is for the legacy agent 5, and you're using the newest image.

Thanks,
Haïssam
