### ISSUE TITLE
How to load API_KEY from a config file instead of environment variable

### ISSUE THREAD

**Issue by nghialv** [DataDog/docker-dd-agent#366]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
(paste your output here)
```

**Additional environment details (Operating System, Cloud provider, etc):**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

At our project, we avoid using the environment variable for configuring all sensitive data.
Can we load API_KEY from a config file currently?

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by hkaj** [comment]
Hey @nghialv I replied in https://github.com/DataDog/datadog-agent/issues/3235 - let's continue the conversation there.
