### ISSUE TITLE
Environment Variable %s is not set

### ISSUE THREAD

**Issue by dsielert** [DataDog/docker-dd-agent#367]
using catalog from rancher configuring with autodiscovery with consul is not working
agent containers won't stay up

```24/2019 3:14:51 PMQuerying Rancher Metadata API
4/24/2019 3:14:51 PMHostname:<omitted>
4/24/2019 3:14:51 PMExporting host labels as host tags:
4/24/2019 3:14:51 PMEnabling Service Discovery
4/24/2019 3:14:51 PMEnvironment variable %s is not set!

**Comment by hkaj** [comment]
Hi @dsielert thanks for reaching out. This repo is for an old agent version and we stopped development there. If you install from rancher you're likely using https://github.com/DataDog/datadog-agent

Also, could you reach out to [support](https://www.datadoghq.com/support/)? We will need more details about your setup to troubleshoot this, and support will ask you about this details on a private channel.

Thanks again
