### ISSUE TITLE
dd-agent info broken as of 5.5 (latest)

### ISSUE THREAD

**Issue by ineu** [DataDog/docker-dd-agent#38]
```
core@staging-1 ~ $ nse datadog-agent
root@staging-1:/# dd-agent info
Traceback (most recent call last):
  File "/usr/bin/dd-agent", line 13, in <module>
    from config import get_version, initialize_logging # noqa
ImportError: No module named config
```
With docker image version 5.4.6 everything is ok.

**Comment by talwai** [comment]
@ineu This is a known issue - sorry about that. We unlinked the `dd-agent` CLI in our 5.5.0 release. The workaround for now is to just create the symlink manually on the host running the agent:
`ln -sf /opt/datadog-agent/agent/agent.py /usr/bin/dd-agent`
You can also run `/opt/datadog-agent/agent/agent.py info` which is equivalent to `dd-agent info`

**Comment by ineu** [comment]
Thanks @talwai.

**Comment by remh** [comment]
@ineu Thanks for the feedback!

 The documented way to get the info page is to run:
`docker exec dd-agent service datadog-agent info` from outside the container
or just:
`service datadog-agent info` from within the container.

`dd-agent info` is not documented and even if it was working it would just display the collector's info.

**Comment by ineu** [comment]
Ok, thank you. Though it's not the best way to do it assuming distros migrate to systemd, so `service` executable will be gone someday.
