### ISSUE TITLE
Command not found: dogstatsd

### ISSUE THREAD

**Issue by jsm** [DataDog/docker-dd-agent#44]
I tried to launch just dogstatsd, but the command isn't in the path. I inspected the container using bash, and I still couldn't find the command anywhere.

**Comment by hkaj** [comment]
Hi @jsm, thanks for raising this issue! Indeed the entrypoints have changed quite a bit and the documentation didn't follow.

As you can see [here](https://github.com/DataDog/dd-agent/blob/40320028af791554ff82ccaadd67891136b4e499/packaging/datadog-agent/source/supervisord.conf#L35-L40), dogstatsd is now actioned by supervisor. It's also started by default when you start the agent container. To manage dogstatsd and the other services you can run `/opt/datadog-agent/bin/supervisorctl -c /etc/dd-agent/supervisor.conf` in the container and use supervisor's commands.

Let me know if you have any other question.
