### ISSUE TITLE
java / Kafka example is incorrect

### ISSUE THREAD

**Issue by sebest** [DataDog/docker-dd-agent#52]
Hello,

I tried the example here: https://github.com/DataDog/docker-dd-agent/blob/master/examples/kafka/Dockerfile

and it does not work, first the '-qq' option masks the main issue by silencing the output, second we need the option '-y' for apt-get install otherwise the build process dies like this:
Do you want to continue? [Y/n] Abort.
2015/11/10 08:29:42 Failed to process json stream error: The command '/bin/sh -c apt-get update     && apt-get install openjdk-7-jre-headless --no-install-recommends     && apt-get clean     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 1

on a side not i think you should provide a docker image with java support (and one without if you are concerned about the size of the final image).

thanx

**Comment by hkaj** [comment]
Hi @sebest, thanks for reporting this. Concerning your side note, we'll look into it. It could take the form of an image tagged `docker-dd-agent:java`. Would that work for you?

**Comment by LotharSee** [comment]
:+1:
