### ISSUE TITLE
Why can't I get the actual hostnames to display in data dog?

### ISSUE THREAD

**Issue by afterthought** [DataDog/docker-dd-agent#55]
Specifically in the list view and when viewing dashboards?
![2015-11-12_1641](https://cloud.githubusercontent.com/assets/198010/11132165/64f0b032-895c-11e5-8455-d9d7487a180d.png)

**Comment by remh** [comment]
Hi @afterthought .
Can you reach out to support@datadoghq.com please ? This is not related to this repo.

Thanks!

**Comment by afterthought** [comment]
Thanks. I just did. I just assumed that dd-agent might be configured incorrectly. We'll see what support says though.
