### ISSUE TITLE
Have dockerfile create VOLUME checks.d

### ISSUE THREAD

**Issue by bradobro** [DataDog/docker-dd-agent#58]
15b52e09bc24ac4347a0b649eb8c488cb06da9f2 breaks the image--it won't run because entrypoint.sh expects to find /checks.d/ and it's not there.

The fix is probably just to add this to the Dockerfile.

```VOLUME ["/conf.d"]```

While doing that, it would be good to check if the `CMD mkdir -p /conf.d` is necessary--I believe it's not.

**Comment by hkaj** [comment]
Fixed by https://github.com/DataDog/docker-dd-agent/commit/74ae747e8bc02b5731ce5bb1c5e9d4a10687cd8c
