### ISSUE TITLE
Using the process check requires to look for processes in /host/proc instead of /proc

### ISSUE THREAD

**Issue by hkaj** [DataDog/docker-dd-agent#60]
As @AshBerlin mentionned (https://twitter.com/AshBerlin/status/674898027283369985) the process check uses psutil to get pids, but psutil retrieves them in `/proc` by default which won't be useful here as the host's pids are in `/host/proc`. However psutil 3.3 allows to change the `/proc` location through `psutil.PROCFS_PATH`. Once https://github.com/DataDog/dd-agent/pull/2134 is merged we need to fix this.

**Comment by hkaj** [comment]
This was fixed by https://github.com/DataDog/dd-agent/pull/2163
closing

**Comment by GaretJax** [comment]
Apparently procfs_path in process.yaml has been deprecated; instead we should set the path inside datadog.conf.

**Comment by GaretJax** [comment]
https://github.com/DataDog/dd-agent/commit/d3421104af5d511acbb3f8be37d9c1506d4dabab
