### ISSUE TITLE
In the case of AWS EC2 Amazon Linux /sys/fs/cgroup should be /cgroup

### ISSUE THREAD

**Issue by Mulkave** [DataDog/docker-dd-agent#7]
Tried to run this on an EC2 Amazon Linux instance:
```bash
docker run -d --privileged --name dd-agent -h hostname -v /var/run/docker.sock:/var/run/docker.sock -v /proc/mounts:/host/proc/mounts:ro -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro -e API_KEY=apikey_3 datadog/docker-dd-agent
```
didn't work, but this did: (replaced `/sys/fs/cgroup` with `/cgroup`

```bash
docker run -d --privileged --name dd-agent -h hostname -v /var/run/docker.sock:/var/run/docker.sock -v /proc/mounts:/host/proc/mounts:ro -v /cgroup/:/host/sys/fs/cgroup:ro -e API_KEY=apikey_3 datadog/docker-dd-agent
```

**Comment by antonmos** [comment]
this fix worked for me to fix "Instance #initialization[ERROR]: Exception("Can't find mounted cgroups. If you run the Agent inside a container, please refer to the documentation.",)" error

**Comment by waisbrot** [comment]
This worked for me, too. I'm running Amazon Linux AMI 2014.09

**Comment by LotharSee** [comment]
This alternative way of mounting cgroups is definitively the good way of doing it. Thanks for sharing it!
I'll update the documentation to expose this solution.

**Comment by alq666** [comment]
Documentation updated.

**Comment by marioizquierdo** [comment]
Just to clarify, the docs now say:
```
Add a volume with the name cgroup and source path of /sys/fs/cgroup/
(or /cgroup/ if you are using an original Amazon Linux AMI)
```
Does this also apply to Amazon Linux AMI v2? or only to the old (original) version?
