### ISSUE TITLE
Don't report Kubernetes pause containers

### ISSUE THREAD

**Issue by therc** [DataDog/docker-dd-agent#74]
Right now there are tens of gcr.io/google_containers/pause containers getting reported (one per running pod in the cluster). These only exist as an artifact of setting up networking and IPC in the pods. They're just adding noise and should be ignored by default (do they count for billing purposes?).

A few approaches:
1. Ignore them in the default Docker config
2. Ignore them in the code
3. Allow setting an environment variable to ignore them, without having to rebuild the image.

Option 3 might be the best because
- the image can be changed through a kubelet flag, e.g. for people using local/private registries
- people might have other containers they want to ignore for whatever reason (I have a few more, actually)

**Comment by hkaj** [comment]
Hi @therc,
Excluding containers is already possible as you can see in [docker_daemon.yaml](https://github.com/DataDog/dd-agent/blob/5.7.3/conf.d/docker.yaml.example#L30-L52). There are currently two ways of using this feature if you're using the containerized agent:
- create your own image based on `datadog/docker-dd-agent` with a customized `docker_daemon.yaml`
- if you can store files on the host beforehand, use the runtime configuration reload as described here: https://github.com/DataDog/docker-dd-agent#enabling-integrations

However it should be made easier for platforms like Kubernetes, we'll look into it.

**Comment by therc** [comment]
I think I can store the file in a Kubernetes 1.2 ConfigMap (a place in cluster-wide storage for configurations and other non-secret items), under the key `docker_daemon.yaml`. Then I can run dd-agent with a volume that exposes the ConfigMap as `/conf.d`. That will create automatically a file in the container under `/conf.d` for each key in the ConfigMap. In this case there'll be just one file. I've done something similar for fluentd.

Thanks! I'll report back if successful so that documentation can be updated.

**Comment by willmore** [comment]
@therc was your ConfigMap method successful?

**Comment by therc** [comment]
Kinda successful. The configmap gets mounted, it's the contents that I still have to get right. :-)

**Comment by therc** [comment]
One limitation is that 1.3 doesn't support exposing ConfigMaps as filenames with underscores in them, because of overzealous validation (it looks for a DNS-valid string).

**Comment by therc** [comment]
I take back the ConfigMap filename comment: you have to create keys without underscores, but when mounting them later, you can use a different filename, adding the underscore back.

**Comment by albertsun** [comment]
@therc was that method ultimately successful? I've tried the same steps, but it seems as though the file from `/conf.d/docker_daemon.yml` does not get copied into `/etc/dd-agent/conf.d/docker_daemon.yml`. I'm wondering if there's some race that happens on container startup where the mounting of the config map happens too late.

**Comment by albertsun** [comment]
Nevermind, I found my bug. I had named the file with `.yml` instead of `.yaml`.

I'm now no longer seeing metrics reported for these pods which is great, but I am still seeing them reported in the count for `docker.containers.running`. Are these containers counted for billing purposes now?

**Comment by hkaj** [comment]
Closing this one as it should be resolved (pause containers are ignored by default). Note that container exclusion doesn't impact `docker.containers.running` as we don't want to lie on the real number of containers managed by your docker daemon, but billing counts on docker.cpu.user so it won't impact what you pay.
Feel free to comment if anything unclear remains.
