### ISSUE TITLE
swarm support?

### ISSUE THREAD

**Issue by cgcgbcbc** [DataDog/docker-dd-agent#82]
is it possible to use swarm host rather than docker socket?

**Comment by hkaj** [comment]
Hi @cgcgbcbc 
Configuring the agent to connect to a Swarm host should work yes. All you have to do is modify this line: https://github.com/DataDog/docker-dd-agent/blob/11.0.573/conf.d/docker_daemon.yaml#L30
to use the node IP/name. There are two ways of doing so: baking that in a custom image on top of ours or using these instructions to override the default `docker_daemon.yaml` with your own file: https://github.com/DataDog/docker-dd-agent#enabling-integrations

Let me know if that helps.

**Comment by hkaj** [comment]
I'll close this issue as it seems to be resolved. Feel free to re-open it should you have more questions.

**Comment by lnkisi** [comment]
is it possible to support docker built-in swarm mode?

**Comment by hkaj** [comment]
@lnkisi the agent already works in swarm mode. By "support" do you mean "collect tags and metrics about it" or did you face an issue running the agent in a swarm-mode cluster?

**Comment by u007** [comment]
hi,
my docker swarm have 2 nodes, 1 is the swarm manager, and another node,
but datadog is only showing manager node services

**Comment by GuillaumeHumbert** [comment]
Hi, @u007 did you figure it out? I just installed a Datadog stack on my Swarm cluster which contains 5 nodes, and only the current node on which the service is running is being monitored.

Does Datadog actually provides monitoring for the entire cluster on which it is installed, or will it ever only monitor the node on which it is running? Do I need to replicate the Datadog service on all nodes for it to monitor the whole cluster?

Thanks

**Comment by u007** [comment]
Hi @GuillaumeHumbert  sorry i couldn't get it to work on multiple node, so i stopped testing datadog

**Comment by hkaj** [comment]
Hi @GuillaumeHumbert, I advise you to create a new issue, and to open it in the [datadog-agent](https://github.com/DataDog/datadog-agent/) repository. docker-dd-agent is for the previous agent version.

That said, the agent only monitors its local node, unless you configure an integration (check) to point to a remote endpoint.
In Swarm (similarly to Kubernetes, Nomad, or DC/OS) you would need to install the agent on every node to get metrics about software running on each node.

If you need more guidance, please open a new issue or a [support ticket](https://docs.datadoghq.com/help/).

**Comment by GuillaumeHumbert** [comment]
Thank you both for your answers, I'll open an issue there.
